export default {
    styles : [
        {
            "featureType":"poi.medical",
            "elementType":"all",
            "stylers":[
                {
                    "visibility":"off"
                }
            ]
        },
        {
            "featureType":"poi.government",
            "elementType":"all",
            "stylers":[
                {
                    "visibility":"on"
                }
            ]
        },
        {
            "featureType":"poi.business",
            "elementType":"all",
            "stylers":[
                {
                    "visibility":"off"
                }
            ]
        },
        {
            "featureType":"poi.place_of_worship",
            "elementType":"all",
            "stylers":[
                {
                    "visibility":"off"
                }
            ]
        },
        {
            "featureType":"poi.attraction",
            "elementType":"all",
            "stylers":[
                {
                    "visibility":"off"
                }
            ]
        },
        {
            "featureType":"poi.sports_complex",
            "elementType":"all",
            "stylers":[
                {
                    "visibility":"on"
                }
            ]
        },
        {
            "featureType":"water",
            "elementType":"geometry",
            "stylers":[
                {
                    "visibility":"on"
                },
                {
                    "color":"#70B5E8"
                },
                {
                    "weight":0.1
                },
                {
                    "lightness":0
                }
            ]
        },
        {
            "featureType":"water",
            "elementType":"labels.text.fill",
            "stylers":[
                {
                    "color":"#ffffff"
                }
            ]
        },
        {
            "featureType":"water",
            "elementType":"labels.text.stroke",
            "stylers":[
                {
                    "visibility":"on"
                },
                {
                    "color":"#70B5E8"
                },
                {
                    "lightness":-20
                }
            ]
        },
        {
            "featureType":"road",
            "elementType":"geometry",
            "stylers":[
                {
                    "color":"#ffffff"
                }
            ]
        },
        {
            "featureType":"road",
            "elementType":"geometry.stroke",
            "stylers":[
                {
                    "visibility":"on"
                },
                {
                    "color":"#dedede"
                }
            ]
        },
        {
            "featureType":"road",
            "elementType":"labels.text.fill",
            "stylers":[
                {
                    "color":"#565656"
                }
            ]
        },
        {
            "featureType":"road",
            "elementType":"labels.text.stroke",
            "stylers":[
                {
                    "visibility":"off"
                }
            ]
        },
        {
            "featureType":"landscape.man_made",
            "elementType":"geometry.fill",
            "stylers":[
                {
                    "color":"#ebebeb"
                }
            ]
        },
        {
            "featureType":"landscape.man_made",
            "elementType":"geometry.stroke",
            "stylers":[
                {
                    "visibility":"off"
                }
            ]
        },
        {
            "featureType":"poi",
            "elementType":"geometry.fill",
            "stylers":[
                {
                    "color":"#ebebeb"
                }
            ]
        },
        {
            "featureType":"poi.park",
            "elementType":"labels.text.fill",
            "stylers":[
                {
                    "color":"#ffffff"
                }
            ]
        },
        {
            "featureType":"poi.park",
            "elementType":"labels.text.stroke",
            "stylers":[
                {
                    "visibility":"on"
                },
                {
                    "color":"#CBDB99"
                },
                {
                    "lightness":-20
                }
            ]
        },
        {
            "featureType":"poi.park",
            "elementType":"geometry",
            "stylers":[
                {
                    "color":"#CBDB99"
                },
                {
                    "weight":0.1
                },
                {
                    "saturation":0
                },
                {
                    "lightness":0
                }
            ]
        },
        {
            "featureType":"transit.line",
            "elementType":"all",
            "stylers":[
                {
                    "visibility":"off"
                }
            ]
        },
        {
            "featureType":"landscape.natural",
            "elementType":"all",
            "stylers":[
                {
                    "visibility":"off"
                }
            ]
        },
        {
            "featureType":"administrative.country",
            "elementType":"labels.text.stroke",
            "stylers":[
                {
                    "visibility":"off"
                }
            ]
        },
        {
            "featureType":"administrative.country",
            "elementType":"geometry.stroke",
            "stylers":[
                {
                    "visibility":"on"
                },
                {
                    "color":"#c7c7c7"
                }
            ]
        },
        {
            "featureType":"administrative.country",
            "elementType":"labels.text.fill",
            "stylers":[
                {
                    "visibility":"on"
                },
                {
                    "color":"#565656"
                }
            ]
        },
        {
            "featureType":"administrative.province",
            "elementType":"labels.text.stroke",
            "stylers":[
                {
                    "visibility":"off"
                }
            ]
        },
        {
            "featureType":"administrative.province",
            "elementType":"labels.text.fill",
            "stylers":[
                {
                    "color":"#565656"
                }
            ]
        },
        {
            "featureType":"administrative.province",
            "elementType":"geometry.stroke",
            "stylers":[
                {
                    "color":"#c7c7c7"
                }
            ]
        },
        {
            "featureType":"administrative.locality",
            "elementType":"labels.text.stroke",
            "stylers":[
                {
                    "visibility":"off"
                }
            ]
        },
        {
            "featureType":"administrative.locality",
            "elementType":"labels.text.fill",
            "stylers":[
                {
                    "color":"#565656"
                }
            ]
        },
        {
            "featureType":"administrative.neighborhood",
            "elementType":"labels.text.stroke",
            "stylers":[
                {
                    "visibility":"off"
                }
            ]
        },
        {
            "featureType":"administrative.neighborhood",
            "elementType":"labels.text.fill",
            "stylers":[
                {
                    "color":"#565656"
                }
            ]
        },
        {
            "featureType":"transit.station",
            "elementType":"labels.text.stroke",
            "stylers":[
                {
                    "visibility":"off"
                }
            ]
        },
        {
            "featureType":"transit.station",
            "elementType":"labels.text.fill",
            "stylers":[
                {
                    "color":"#565656"
                }
            ]
        }
    ]
};
