/** App Channel **/
export const APP_CHANNEL = 'APP_CHANNEL';
export const APP_LOADING_START = 'APP_LOADING_START';
export const APP_LOADING_END = 'APP_LOADING_END';
export const APP_NOTIFICATION = 'APP_NOTIFICATION';


/** User Channel **/
export const APP_USER_CHANNEL = 'APP_USER_CHANNEL';
export const APP_USER_FETCH = 'APP_USER_FETCH';
export const APP_USER_FETCH_SUCCESS = 'APP_USER_FETCH_SUCCESS';

export const APP_USER = 'APP_USER';
export const APP_USER_IS_AUTHENTICATED = 'APP_USER_IS_AUTHENTICATED';

export const APP_USER_LOGIN = 'APP_USER_LOGIN';
export const APP_USER_LOGIN_SUCCESS = 'APP_USER_LOGIN_SUCCESS';
export const APP_USER_LOGIN_ERROR = 'APP_USER_LOGIN_ERROR';

export const APP_USER_SIGNUP = 'APP_USER_SIGNUP';
export const APP_USER_SIGNUP_SUCCESS = 'APP_USER_SIGNUP_SUCCESS';
export const APP_USER_SIGNUP_ERROR = 'APP_USER_SIGNUP_ERROR';

export const APP_USER_LOGOUT = 'APP_USER_LOGOUT';
export const APP_USER_LOGOUT_SUCCESS = 'APP_USER_LOGOUT_SUCCESS';
export const APP_USER_LOGOUT_ERROR = 'APP_USER_LOGOUT_ERROR';


/** User Channel **/
export const LAYOUT_CHANNEL = 'LAYOUT_CHANNEL';
export const CLOSE_REGION = 'CLOSE_REGION';
